otp/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import logout
from .views import ( RegisterView, DashboardView,
                    LoginView, PhoneVerificationView,
                    IndexView,view1)
from django.contrib.auth import views as auth_views

app_name='accounts'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index_page'),
    url(r'^register/$', RegisterView.as_view(), name="register_url"),
    url(r'^login/', view1, name="login_url"),
    url(r'^verify/$', PhoneVerificationView, name="phone_verification_url"),
    url(r'^dashboard/$', DashboardView.as_view(), name="dashboard_url"),
    url(r'^xyz/$', LoginView,name="LoginView"),
    url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),

]

otp/otp/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from accounts.api import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    path('account_api/', include(urls)),
]

otp/accounts/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext as _
# from django.contrib.auth.password_validation import validate_password
from django.contrib.auth import authenticate

from .models import User


class RegisterForm(forms.ModelForm):

    # phone_number = forms.IntegerField(required=True)
    # password1 = forms.CharField(widget=forms.PasswordInput())
    # password2 = forms.CharField(widget=forms.PasswordInput())
    # country_code = forms.IntegerField()

    # MIN_LENGTH = 4

    class Meta:
        model = User
        fields = ['country_code','phone_number',
                  'full_name' ]  # 'username' 'password1', 'password2',

    # def clean_username(self):
    #     username = self.data.get('username')
    #     return username

    # def clean_password1(self):
    #     password = self.data.get('password1')
    #     validate_password(password)
    #     if password != self.data.get('password2'):
    #         raise forms.ValidationError(_("Passwords do not match"))
    #     return password

    def clean_phone_number(self):
        phone_number = self.data.get('phone_number')
        if User.objects.filter(phone_number=phone_number).exists():
            raise forms.ValidationError(
                _("Another user with this phone number already exists"))
        return phone_number

    def save(self, *args, **kwargs):
        user = super(RegisterForm, self).save(*args, **kwargs)
        # user.set_password(self.cleaned_data['password1'])
        print('Saving user with country_code', user.country_code)
        user.save()
        return user


class PhoneVerificationForm(forms.Form):
    one_time_password = forms.IntegerField()

    class Meta:
        fields = ['one_time_password',]



class LoginForm(forms.Form):
    # username = forms.CharField()
    # phone_number=forms.IntegerField(unique=True)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields =  ['phone_number']             #['username','password']

    # def clean(self):
    #     # username = self.cleaned_data.get('username')
    #     phone_number=self.cleaned_data.get('phone_number')
    #     # password = self.cleaned_data.get('password')
    #     # user = authenticate(username=phone_number, password=password)
    #
    #     if not user:
    #         raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
    #     return self.cleaned_data
    #
    # def login(self, request):
    #     username = self.cleaned_data.get('username')
    #     password = self.cleaned_data.get('password')
    #     user = authenticate(username=username, password=password)
    #     return user

    def save(self, *args, **kwargs):
        user = super(LoginForm, self).save(*args, **kwargs)
        # user.set_password(self.cleaned_data['password1'])
        print('Saving user with country_code', user.phone_number)
        user.save()
        return user

otp/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <title>Dashboard</title>
</head>
<body>
  <div class="jumbotron">
    <div class="container">
      {% if messages %}
      <div id="messages">
        {% for message in messages %}
        <div class="alert alert-dismissible alert-info"
             role="alert">
          <button type="button" class="close" data-dismiss="alert"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message|escape }}
        </div>
        {% endfor %}
      </div>
      {% endif %}
    <h1>Yahoo logged in!</h1>
    <br><br>
    <div class="table-responsive">
      <table class="table">
        <tr>
          <td>
            Name : {{user.full_name}}
            <br>
            Phone : +{{user.country_code}} {{user.phone_number}}
            <!-- <br>
            Username : {{user.get_username}}
            <br> -->
          </td>
          <td>
          <!-- Account Verified: {{user.phone_number_verified}} -->
          <br>
          <!-- <form action="" method="post">
            {% csrf_token %}
            Two Factor Authentication:
              {%if user.two_factor_auth %}
              <button type="submit" class="btn btn-success" name="two_factor_auth">
                ENABLED
              {%else%}
              <button type="submit" class="btn btn-danger" name="two_factor_auth">
                DISABLED
              {%endif%}
            </button>
            Click to toggle.
          </form> -->

        </tr>
      </table>

</div>
    <a href="/logout"  class="btn btn-danger">Logout</a>
  </div>
  </div>
  <script src="/static/js/jquery.min.js" charset="utf-8"></script>
  <script src="/static/js/bootstrap.min.js" charset="utf-8"></script></body>
</html>

otp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <title>Home</title>

</head>
<body>
  <div class="jumbotron">
    <div class="container" >
      {% if messages %}
      <div id="messages">
        {% for message in messages %}
        <div class="alert alert-dismissible alert-info"
             role="alert">
          <button type="button" class="close" data-dismiss="alert"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message|escape }}
        </div>
        {% endfor %}
      </div>
      {% endif %}
      <div class="row">

    <div class="center-block" style="width:500px;">
      <h3>Twilio Project</h3>
      <h4>A small django website with Authy Phone Verification API</h4>
      <h4>Features</h4>
      <h5>Phone number verification after user registration</h5>
      <h5>Two-factor authentication</h5>
      <h5>Custom User Model</h5>
<br>
      <!-- <h4>For details visit my <a href="https://rishabhiitbhu.wordpress.com/2017/03/15/twilio-project/">blog</a></h4> -->
    <br>
    <br>
    <a href="/register" class="btn btn-default">Register</a>
    <a href="/login" class="btn btn-info">Login</a>

  </div>
  </div>
  </div>
  <footer class="navbar-fixed-bottom">
    <!-- <div class="center-block" style="width:500px;">

    <p >Made with <3 by <a href="https://github.com/rishabhiitbhu">Rishabh Agrahari</a></p>
    </div> -->
  </footer>
</div>
  <script src="/static/js/jquery.min.js" charset="utf-8"></script>
  <script src="/static/js/bootstrap.min.js" charset="utf-8"></script>
</body>
</html>

otp/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Eatler</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">


    </head>

  <body>
<div class="jumbotron">

    <div class="container">

      <div class="col-sm-6 col-sm-offset-3">


      {% block content %}
      {% if messages %}
      <div id="messages">
        {% for message in messages %}
        <div class="alert alert-dismissible alert-info"
             role="alert">
          <button type="button" class="close" data-dismiss="alert"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message|escape }}
        </div>
        {% endfor %}
      </div>
      {% endif %}
      {% if form.non_field_errors %}
      <div id="messages">
        {% for message in form.non_field_errors %}
        <div class="alert alert-dismissible alert-danger"
             role="alert">
          <button type="button" class="close" data-dismiss="alert"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message|escape }}
        </div>
        {% endfor %}
      </div>
      {% endif %}

      <form class="account-register form-narrow" id="login_form" method="POST"
            action="{% url "accounts:LoginView" %}" >
        <h3>Login</h3>

        {% csrf_token %}

        <!-- <div class="form-group{% if form.username.errors %} has-error{% endif %}">
          <label class="control-label" for="id_username">Username</label>
              <input class="form-control input-lg" id="id_username" maxlength="150" name="username" type="text" required />
          <div class="error-block">{{ form.username.errors }}</div>
        </div> -->

        <div class="form-group{% if form.phone_number.errors %} has-error{% endif %}">
          <label class="control-label" for="id_username">Phone Number</label>
              <input class="form-control input-lg" id="id_username" maxlength="150" name="phone_number" type="text" required />
          <div class="error-block">{{ form.phone_number.errors }}</div>
        </div>

<!--
        <div class="form-group{% if form.password.errors %} has-error{% endif %}">
          <label class="control-label" for="id_password">Password</label>
          <div class="input-group input-group-lg"> -->
<!--
          </div>
          <input class="form-control input-lg" id="id_password" name="password" type="password" required />
          <div class="error-block">{{ form.password.errors }}</div>
        </div> -->


        <button type="submit" name="register"
                class="btn btn-primary btn-lg btn-block text-uppercase">
          Login
        </button>

        <p class="text-center">
        Don't have an account? <a href="/">Register</a>
        </p>
      </form>

      {% endblock %}
</div>
    </div> <!-- /container -->

  </div>
  <script src="/static/js/jquery.min.js" charset="utf-8"></script>
  <script src="/static/js/bootstrap.min.js" charset="utf-8"></script>
  </body>
</html>

otp/templates/phone_confirm.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Eatler</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">


    </head>

  <body>
<div class="jumbotron">

    <div class="container">

      <div class="col-sm-6 col-sm-offset-3">


      {% block content %}

      {% if messages %}
      <div id="messages">
        {% for message in messages %}
        <div class="alert alert-dismissible alert-info"
             role="alert">
          <button type="button" class="close" data-dismiss="alert"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message|escape }}
        </div>
        {% endfor %}
      </div>
      {% endif %}

      <form class="form-inline" id="login_form" method="POST" action="/verify/" >
        <h3>Confirm your phone number</h3>
        <br>
        {% csrf_token %}
        <!-- <input type='hidden' name='username' value='{{user.username}}' />

        <div class="form-group{% if form.one_time_password.errors %} has-error{% endif %}">
          <label class="control-label" for="id_one_time_password">One Time Password</label>
          <div class="input-group input-group-lg">

          </div>
          <input class="form-control input-lg" id="id_one_time_password" name="one_time_password" type="password" required />
          <div class="error-block">{{ form.one_time_password.errors }}</div>
        </div> -->
        <input type='hidden' name='phone_number' value='{{user.phone_number}}' />

        <div class="form-group{% if form.one_time_password.errors %} has-error{% endif %}">
          <label class="control-label" for="id_one_time_password">One Time Password</label>
          <div class="input-group input-group-lg">

          </div>
          <input class="form-control input-lg" id="id_one_time_password" name="one_time_password" type="password" required />
          <div class="error-block">{{ form.one_time_password.errors }}</div>
        </div>


        <button type="submit" name="register"
                class="btn btn-primary btn-lg ">
        Confirm
        </button>
        <br><br>
        <p class="text-center">
        Didn't recieve one time password? <a href="/resend_otp">Resend OTP</a>
        </p>
      </form>

      {% endblock %}
</div>
    </div> <!-- /container -->

  </div>

  </body>
</html>